### ISSUE TITLE
bicleaner-hardrules exits with exit status 0 on error

### ISSUE THREAD

**Issue by jelmervdl** [bitextor/bicleaner-hardrules#1]
For example, if one side of the sentence pair is empty, bicleaner-hardrules will thrown an error because of division by zero. However, the overall process still "completes successfully" which makes it hard to detect errors (other than counting the number of output lines)

For example, the test.tsv file has one line with an empty tcol field (so just two tabs after each other really) which will crash hardrules.py. I do not expect "ok" to be printed afterwards, but it is.
```
$ bicleaner-hardrules --score_only --processes 1 --source_lang en --target_lang pt --scol 3 --tcol 4 --metadata ~/r/jelmervdl/bicleaner-models/full/en-pt/metadata.yaml < ~/test.tsv && echo ok

2021-07-05 09:43:34,749 - INFO - Loading metadata info
Warning : `load_model` does not return WordVectorModel or SupervisedModel any more, but a `FastText` object which is very similar.
2021-07-05 09:43:34,761 - INFO - Executing main program...
2021-07-05 09:43:34,761 - INFO - Starting process
2021-07-05 09:43:34,761 - INFO - Running 1 workers at 10000 rows per block
2021-07-05 09:43:34,764 - INFO - Start mapping
2021-07-05 09:43:34,767 - INFO - End mapping
Process Process-2:
Traceback (most recent call last):
  File "/home/cs-vand1/src/cirrus-scripts/env/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/cs-vand1/src/cirrus-scripts/env/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cs-vand1/src/cirrus-scripts/env/lib/python3.8/site-packages/hardrules/bicleaner_hardrules.py", line 258, in worker_process
    wrong_tu_results = wrong_tu(left,right, args, lm_filter, porn_removal, porn_tokenizer)
  File "/home/cs-vand1/src/cirrus-scripts/env/lib/python3.8/site-packages/hardrules/hardrules.py", line 174, in wrong_tu
    elif not (c_length(left, right) or c_length_bytes(left, right)):
  File "/home/cs-vand1/src/cirrus-scripts/env/lib/python3.8/site-packages/hardrules/hardrules.py", line 49, in c_length
    return 0.5 <= float(len(left))/float(len(right)) <= 2.0
ZeroDivisionError: float division by zero
2021-07-05 09:43:35,001 - INFO - Hard rules applied. Output available in <stdout>
2021-07-05 09:43:35,004 - INFO - Finished
2021-07-05 09:43:35,004 - INFO - Total: 100 rows
2021-07-05 09:43:35,005 - INFO - Elapsed time 0.24 s
2021-07-05 09:43:35,005 - INFO - Troughput: 410 rows/s
2021-07-05 09:43:35,005 - INFO - Program finished
ok
```

**Comment by ZJaume** [comment]
Wow, we didn't noticed that hardrules fails when empty side because bicleaner does not call `wrong_tu` function from hardrules if one side is empty. I'm gonna fix that and the sentences with an empty side will be tagged as 0. I will also return 1 if any process encounters errors.

**Comment by jelmervdl** [comment]
Normally I would not expect empty columns in the input to bicleaner-hardrules. In this case it was a column with just (incomplete?) soft hyphen characters which got removed by bifixer, which I directly stream into bicleaner-hardrules.

**Comment by ZJaume** [comment]
It is now fixed in dev, could you please install from there and tell me if it works? I'll make a new release if everything is ok.

**Comment by jelmervdl** [comment]
The original issue with the empty column is fixed.

I also tried what would happen if I give it corrupt input (e.g. not enough columns) but it does not fail and instead skips the line in the output (and prints a warning):
`2021-07-05 12:25:27,099 - ERROR - WARNING: scol (3) or tcol (4) indexes above column number (2)`

I'd rather see it fail hard (especially in --score_only mode) cause now I end up with output that does not align with the input. It also would indicate something further up the pipeline being bad, which I'd rather not go see unnoticed.

**Comment by ZJaume** [comment]
Pushed the change to dev, this also will need to be fixed in bicleaner and bicleaner ai.

**Comment by ZJaume** [comment]
Changed, now prints a 0 for wrong column number, and therefore the resulting number of lines will be the same with score only mode.
