### ISSUE TITLE
Package on pypi for 2.10.1 is missing kenlm source

### ISSUE THREAD

**Issue by jelmervdl** [bitextor/bicleaner-hardrules#10]
Edit: real problem might be missing wheels, see below :D

It looks like the latest version on Pypi is missing the kenlm folder that's a submodule here in the repo.

When I tried to install bicleaner, I hit this error mentioning bicleaner-hardrules:

```
> pip download bicleaner-hardrules==2.10.1
Collecting bicleaner-hardrules==2.10.1
  Using cached bicleaner-hardrules-2.10.1.tar.gz (60 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [11 lines of output]
      Traceback (most recent call last):
        File "/private/var/folders/dc/wd4f060x3ms829gcm4dthzzm0000gn/T/pip-build-env-xfu5mi6b/overlay/lib/python3.9/site-packages/skbuild/setuptools_wrap.py", line 447, in setup
          _check_skbuild_parameters(cmake_install_dir, cmake_source_dir)
        File "/private/var/folders/dc/wd4f060x3ms829gcm4dthzzm0000gn/T/pip-build-env-xfu5mi6b/overlay/lib/python3.9/site-packages/skbuild/setuptools_wrap.py", line 295, in _check_skbuild_parameters
          raise SKBuildError(msg)


        setup parameter 'cmake_source_dir' set to a nonexistent directory.
          Project Root  : /private/var/folders/dc/wd4f060x3ms829gcm4dthzzm0000gn/T/pip-download-inc_mjwi/bicleaner-hardrules_0b468cb3aacd443789fe8acf1017bd89
          CMake Source Directory: ./kenlm

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

I downloaded the tar from pypi to check, and indeed, no kenlm:
```
> tree bicleaner-hardrules-2.10.1/
 ├
 ├ .github
 │  ├ stale.yml
 ├ .gitignore
 ├ .gitmodules
 ├ CHANGELOG.md
 ├ LICENSE
 ├ PKG-INFO
 ├ README.md
 ├ pyproject.toml
 ├ scripts
 │  ├ convert_to_generic_platform_wheel.py
 │  ├ release.sh
 ├ setup.cfg
 ├ setup.py
 ├ src
 │  ├ bicleaner_hardrules.egg-info
 │  │  ├ PKG-INFO
 │  │  ├ SOURCES.txt
 │  │  ├ dependency_links.txt
 │  │  ├ entry_points.txt
 │  │  ├ requires.txt
 │  │  ├ top_level.txt
 │  ├ hardrules
 │  │  ├ __init__.py
 │  │  ├ bicleaner_hardrules.py
 │  │  ├ hardrules.py
 │  │  ├ lm.py
 │  │  ├ tokenizer.py
 │  │  ├ training.py
 │  │  ├ util.py
 │  │  ├ writing_scripts.py
 ├ tests
 │  ├ hardrules_test.py
 │  └ test-corpus.en-de
```

Note that this might normally not have been an issue because previous releases had wheels uploaded to pypi. But there's no wheel for 2.10.1. There's a `scripts/release.sh` file that seems to do the right thing, but it might not have run successfully for 2.10.1?

**Comment by ZJaume** [comment]
I have no idea what happended, but it should be fixed now.

**Comment by jelmervdl** [comment]
Thanks :D
